import connectDB from '../lib/mongodb'
import MenuItem from '../lib/models/MenuItem'

const menuItems = [
  // Paradise Biryani (restaurantId from your DB)
  {
    restaurantId: 'paradise-biryani',
    name: 'Hyderabadi Chicken Dum Biryani',
    description: 'Authentic Hyderabadi style chicken biryani slow-cooked with aromatic basmati rice and traditional spices',
    price: 350,
    category: 'Biryani',
    isVeg: false,
    imageUrl: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=400',
    rating: 4.6,
    preparationTime: 25,
    spiceLevel: 'medium',
    tags: ['bestseller', 'signature'],
  },
  {
    restaurantId: 'paradise-biryani',
    name: 'Mutton Biryani',
    description: 'Tender mutton pieces layered with fragrant rice, slow-cooked to perfection',
    price: 450,
    category: 'Biryani',
    isVeg: false,
    imageUrl: 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?w=400',
    rating: 4.8,
    preparationTime: 35,
    spiceLevel: 'hot',
    tags: ['premium', 'chef-special'],
  },
  {
    restaurantId: 'paradise-biryani',
    name: 'Veg Biryani',
    description: 'Mixed vegetables cooked with aromatic spices and basmati rice',
    price: 250,
    category: 'Biryani',
    isVeg: true,
    imageUrl: 'https://images.unsplash.com/photo-1596797038530-2c107229654b?w=400',
    rating: 4.3,
    preparationTime: 20,
    spiceLevel: 'mild',
    tags: ['vegetarian'],
  },
  {
    restaurantId: 'paradise-biryani',
    name: 'Chicken 65',
    description: 'Spicy and crispy fried chicken with curry leaves and green chillies',
    price: 280,
    category: 'Starters',
    isVeg: false,
    imageUrl: 'https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?w=400',
    rating: 4.5,
    preparationTime: 15,
    spiceLevel: 'hot',
    tags: ['spicy', 'crispy'],
  },
  {
    restaurantId: 'paradise-biryani',
    name: 'Paneer 65',
    description: 'Crispy fried paneer tossed in spicy masala',
    price: 250,
    category: 'Starters',
    isVeg: true,
    imageUrl: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=400',
    rating: 4.2,
    preparationTime: 15,
    spiceLevel: 'medium',
    tags: ['vegetarian', 'spicy'],
  },
  {
    restaurantId: 'paradise-biryani',
    name: 'Double Ka Meetha',
    description: 'Traditional Hyderabadi dessert made with bread, milk, and dry fruits',
    price: 120,
    category: 'Desserts',
    isVeg: true,
    imageUrl: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400',
    rating: 4.4,
    preparationTime: 5,
    tags: ['sweet', 'traditional'],
  },
  {
    restaurantId: 'paradise-biryani',
    name: 'Butter Naan',
    description: 'Soft and fluffy Indian bread with butter',
    price: 50,
    category: 'Breads',
    isVeg: true,
    imageUrl: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=400',
    rating: 4.3,
    preparationTime: 10,
    tags: ['vegetarian'],
  },
  {
    restaurantId: 'paradise-biryani',
    name: 'Raita',
    description: 'Cooling yogurt with cucumber and spices',
    price: 60,
    category: 'Beverages',
    isVeg: true,
    imageUrl: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400',
    rating: 4.0,
    preparationTime: 5,
    tags: ['healthy', 'cooling'],
  },

  // Domino's Pizza
  {
    restaurantId: 'dominos',
    name: 'Farmhouse Pizza',
    description: 'Loaded with onion, capsicum, tomato, mushroom, and cheese',
    price: 399,
    category: 'Main Course',
    isVeg: true,
    imageUrl: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=400',
    rating: 4.4,
    preparationTime: 25,
    tags: ['bestseller', 'vegetarian'],
  },
  {
    restaurantId: 'dominos',
    name: 'Chicken Pepperoni',
    description: 'Classic pepperoni with mozzarella cheese and tangy sauce',
    price: 499,
    category: 'Main Course',
    isVeg: false,
    imageUrl: 'https://images.unsplash.com/photo-1628840042765-356cda07504e?w=400',
    rating: 4.6,
    preparationTime: 25,
    spiceLevel: 'mild',
    tags: ['bestseller', 'non-veg'],
  },
  {
    restaurantId: 'dominos',
    name: 'Margherita Pizza',
    description: 'Classic pizza with cheese and tomato sauce',
    price: 299,
    category: 'Main Course',
    isVeg: true,
    imageUrl: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=400',
    rating: 4.2,
    preparationTime: 20,
    tags: ['classic', 'vegetarian'],
  },
  {
    restaurantId: 'dominos',
    name: 'Cheesy Garlic Bread',
    description: 'Freshly baked bread with garlic butter and mozzarella',
    price: 149,
    category: 'Starters',
    isVeg: true,
    imageUrl: 'https://images.unsplash.com/photo-1573140401552-388e17f0e5d2?w=400',
    rating: 4.5,
    preparationTime: 15,
    tags: ['vegetarian', 'garlic'],
  },
  {
    restaurantId: 'dominos',
    name: 'Chicken Wings',
    description: 'Spicy grilled chicken wings with BBQ sauce',
    price: 249,
    category: 'Starters',
    isVeg: false,
    imageUrl: 'https://images.unsplash.com/photo-1608039829572-78524f79c4c7?w=400',
    rating: 4.3,
    preparationTime: 20,
    spiceLevel: 'medium',
    tags: ['spicy', 'grilled'],
  },
  {
    restaurantId: 'dominos',
    name: 'Choco Lava Cake',
    description: 'Warm chocolate cake with molten chocolate center',
    price: 99,
    category: 'Desserts',
    isVeg: true,
    imageUrl: 'https://images.unsplash.com/photo-1606313564558-b1e2da0c6a15?w=400',
    rating: 4.7,
    preparationTime: 10,
    tags: ['sweet', 'chocolate'],
  },
  {
    restaurantId: 'dominos',
    name: 'Pepsi (500ml)',
    description: 'Chilled soft drink',
    price: 60,
    category: 'Beverages',
    isVeg: true,
    imageUrl: 'https://images.unsplash.com/photo-1554866585-cd94860890b7?w=400',
    rating: 4.0,
    preparationTime: 2,
    tags: ['cold-drink'],
  },

  // McDonald's
  {
    restaurantId: 'mcdonalds',
    name: 'McChicken Burger',
    description: 'Crispy chicken patty with lettuce and mayo',
    price: 180,
    category: 'Main Course',
    isVeg: false,
    imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400',
    rating: 4.3,
    preparationTime: 12,
    tags: ['bestseller'],
  },
  {
    restaurantId: 'mcdonalds',
    name: 'McSpicy Paneer Burger',
    description: 'Spicy paneer patty with fresh vegetables',
    price: 160,
    category: 'Main Course',
    isVeg: true,
    imageUrl: 'https://images.unsplash.com/photo-1550547660-d9450f859349?w=400',
    rating: 4.4,
    preparationTime: 12,
    spiceLevel: 'medium',
    tags: ['vegetarian', 'spicy'],
  },
  {
    restaurantId: 'mcdonalds',
    name: 'French Fries (Medium)',
    description: 'Crispy golden fries with salt',
    price: 100,
    category: 'Starters',
    isVeg: true,
    imageUrl: 'https://images.unsplash.com/photo-1576107232684-1279f390859f?w=400',
    rating: 4.6,
    preparationTime: 8,
    tags: ['vegetarian', 'crispy'],
  },
  {
    restaurantId: 'mcdonalds',
    name: 'Chicken McNuggets (6pc)',
    description: 'Tender chicken pieces with crispy coating',
    price: 180,
    category: 'Starters',
    isVeg: false,
    imageUrl: 'https://images.unsplash.com/photo-1562967914-608f82629710?w=400',
    rating: 4.5,
    preparationTime: 10,
    tags: ['crispy', 'chicken'],
  },
  {
    restaurantId: 'mcdonalds',
    name: 'McFlurry Oreo',
    description: 'Soft serve ice cream with Oreo cookie pieces',
    price: 120,
    category: 'Desserts',
    isVeg: true,
    imageUrl: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=400',
    rating: 4.6,
    preparationTime: 5,
    tags: ['sweet', 'cold'],
  },
  {
    restaurantId: 'mcdonalds',
    name: 'Coca-Cola (Medium)',
    description: 'Chilled Coke',
    price: 80,
    category: 'Beverages',
    isVeg: true,
    imageUrl: 'https://images.unsplash.com/photo-1554866585-cd94860890b7?w=400',
    rating: 4.2,
    preparationTime: 2,
    tags: ['cold-drink'],
  },

  // Add a few items for other restaurants too
  {
    restaurantId: 'kfc',
    name: 'Hot & Crispy Chicken',
    description: '2 pieces of signature crispy fried chicken',
    price: 280,
    category: 'Main Course',
    isVeg: false,
    imageUrl: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=400',
    rating: 4.7,
    preparationTime: 15,
    spiceLevel: 'medium',
    tags: ['bestseller', 'crispy'],
  },
  {
    restaurantId: 'kfc',
    name: 'Chicken Popcorn',
    description: 'Bite-sized crispy chicken pieces',
    price: 180,
    category: 'Starters',
    isVeg: false,
    imageUrl: 'https://images.unsplash.com/photo-1562967914-608f82629710?w=400',
    rating: 4.5,
    preparationTime: 10,
    tags: ['snack', 'crispy'],
  },
  {
    restaurantId: 'subway',
    name: 'Veggie Delite Sub (6 inch)',
    description: 'Fresh vegetables with cheese and sauces',
    price: 150,
    category: 'Main Course',
    isVeg: true,
    imageUrl: 'https://images.unsplash.com/photo-1579162851944-77b6b3c094dc?w=400',
    rating: 4.2,
    preparationTime: 10,
    tags: ['healthy', 'vegetarian'],
  },
  {
    restaurantId: 'subway',
    name: 'Chicken Teriyaki Sub (6 inch)',
    description: 'Grilled chicken with teriyaki sauce and vegetables',
    price: 200,
    category: 'Main Course',
    isVeg: false,
    imageUrl: 'https://images.unsplash.com/photo-1579162851944-77b6b3c094dc?w=400',
    rating: 4.4,
    preparationTime: 12,
    tags: ['healthy', 'grilled'],
  },
]

async function seedMenuItems() {
  try {
    await connectDB()
    console.log('Connected to MongoDB')

    // Clear existing menu items
    await MenuItem.deleteMany({})
    console.log('Cleared existing menu items')

    // Insert new menu items
    const result = await MenuItem.insertMany(menuItems)
    console.log(`✅ Successfully seeded ${result.length} menu items`)

    // Show summary
    const summary = await MenuItem.aggregate([
      {
        $group: {
          _id: '$restaurantId',
          count: { $sum: 1 },
          categories: { $addToSet: '$category' },
        },
      },
    ])

    console.log('\n📊 Menu Items Summary:')
    summary.forEach((item) => {
      console.log(`   ${item._id}: ${item.count} items (${item.categories.join(', ')})`)
    })

    process.exit(0)
  } catch (error) {
    console.error('❌ Error seeding menu items:', error)
    process.exit(1)
  }
}

seedMenuItems()
